### ISSUE TITLE
NDI Python version

### ISSUE THREAD

**Issue by TonyTheDarkLord** [paratustra/tvadblocker#1]
Recien baje el repo y lo deje funcional, sos un groso, me costo que detecte el logo pero lo logre, y le agregue tiempo a 10 segundos entre chequeo por un tema de performance.  ( no te volvi a encontrar en instagram para agradecerte )

Como dato que me pasó es que por el  ndi-python la máxima versión de python debe ser 3.10 y adicional yo uso la versión 27.2.4 por un tema de compatibilidad con otros plugins y funca 10 puntos, por si lo queres agregar/cambiar al readme.

Esta en produccion para ver el mundial 😎

![2022-11-26_13-55](https://user-images.githubusercontent.com/7749082/204100095-20440457-51d1-44cc-8201-0fe59db4eb1c.png)

**Comment by paratustra** [comment]
excelente. cuando pueda lo arreglo. es el primer script que hago para que lo usen otros así que obviamente iban a haber desprolijidades jaja! posta muchas gracias!
